version: "3.8"

services:
  vpn:
    image: gartnera/openconnect
    environment:
      - SERVER=devnetsandbox-usw1-reservation.cisco.com:20274
      - USERNAME=gabriel.ro
      - PASSWORD=EDQUEECB
    command: ["openconnect", "-u", "${USERNAME}", "--passwd-on-stdin", "${SERVER}"]
    stdin_open: true
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - node-webapp-network
    ports:
      - "0.0.0.0::8001:8001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=admin
    networks:
      - node-webapp-network
openconnect:
  image: vimagick/openconnect
  command: https://vpn.easypi.info:4443
  net: host
  volumes:
    - ./data:/etc/openconnect
  stop_signal: SIGINT
  privileged: yes
networks:
  node-webapp-network:
    driver: bridge
volumes:
  mongodb: 